### ISSUE TITLE
Unable to build app on Manjaro

### ISSUE THREAD

**Issue by aitbw** [hql287/Manta#138]
Please answer these question so I can help you faster.

**Is it a bug or a feature request?**

- [x] It's a bug.
- [ ] I'm requesting a new feature.

**Which version are you using?**

- [ ] macOS
- [ ] Windows
- [x] Linux

**Which is the version/distribution of the OS?**

Manjaro Linux with Linux Kernel 4.14.12

**Describe your issue**

I'm trying to build Manta on my laptop but after cloning the project and installing its dependencies, the `yarn release:linux` task fails.

Here's the backtrace:

```
yarn run v1.3.2
$ yarn run build && yarn run dist:linux
$ webpack --env.production
clean-webpack-plugin: /home/aitbw/apps/Manta/prod has been removed.
Hash: faa35bd3450b1f1c0fb5
Version: webpack 3.8.1
Time: 13205ms
              Asset     Size  Chunks             Chunk Names
       main.prod.js   198 kB       0  [emitted]  main
    preview.prod.js  53.2 kB       1  [emitted]  preview
       tour.prod.js  15.4 kB       2  [emitted]  tour
      modal.prod.js  1.75 kB       3  [emitted]  modal
     vendor.prod.js  13.6 kB       4  [emitted]  vendor
   main.prod.js.map   244 kB       0  [emitted]  main
preview.prod.js.map    59 kB       1  [emitted]  preview
   tour.prod.js.map  17.2 kB       2  [emitted]  tour
  modal.prod.js.map  3.98 kB       3  [emitted]  modal
 vendor.prod.js.map  24.9 kB       4  [emitted]  vendor
  [11] ./libs/dragNdrop.js 464 bytes {0} {1} {2} {3} [built]
  [12] ./app/renderers/dialog.js 957 bytes {0} [built]
  [53] multi react-hot-loader/patch ./tour/index.jsx 40 bytes {2} [built]
  [56] ./tour/index.jsx 817 bytes {2} [built]
  [69] multi react-hot-loader/patch ./app/renderers/startup.js ./app/renderers/dialog.js ./app/renderers/menu.js ./app/index.jsx 76 bytes {0} [built]
  [70] ./app/renderers/startup.js 221 bytes {0} [built]
  [74] ./app/renderers/menu.js 4.87 kB {0} [built]
  [75] ./app/index.jsx 1.15 kB {0} [built]
  [76] ./app/store/index.jsx 2.59 kB {0} [built]
  [87] ./app/App.jsx 7.31 kB {0} [built]
 [126] multi react-hot-loader/patch ./preview/index.jsx 40 bytes {1} [built]
 [127] ./preview/index.jsx 1.72 kB {1} [built]
 [128] ./preview/Viewer.jsx 1.44 kB {1} [built]
 [148] multi react-hot-loader/patch ./modal/index.js 40 bytes {3} [built]
 [149] ./modal/index.js 2.42 kB {3} [built]
    + 135 hidden modules

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (100 kB). This can impact web performance.
Entrypoints:
  main (212 kB)
      vendor.prod.js
      main.prod.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
$ electron-builder --linux
electron-builder 19.45.5
Using electron-builder.yml configuration file
No native production dependencies
Packaging for linux x64 using electron 1.7.9 to dist/linux-unpacked
Building AppImage for arch x64
Building Snap for arch x64
⚠️  Application category is not set for Linux (linux.category).
Please see https://electron.build/configuration/configuration#LinuxBuildOptions-category
 Cannot map mac category "public.app-category.business" to Linux. If possible mapping is known for you, please file issue to add it.
Error: spawn snapcraft ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at spawn (/home/aitbw/apps/Manta/node_modules/electron-builder/node_modules/builder-util/src/util.ts:182:3)
    at /home/aitbw/apps/Manta/node_modules/electron-builder/src/targets/snap.ts:163:7
    at Generator.next (<anonymous>)
    at /home/aitbw/apps/Manta/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/aitbw/apps/Manta/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at SnapTarget.build (/home/aitbw/apps/Manta/node_modules/electron-builder/out/targets/snap.js:189:11)
    at taskManager.addTask.default.map.it (/home/aitbw/apps/Manta/node_modules/electron-builder/src/platformPackager.ts:120:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/aitbw/apps/Manta/node_modules/electron-builder/src/platformPackager.ts:120:41)
    at /home/aitbw/apps/Manta/node_modules/electron-builder/src/platformPackager.ts:116:10
From previous event:
    at LinuxPackager.pack (/home/aitbw/apps/Manta/node_modules/electron-builder/out/platformPackager.js:190:11)
    at /home/aitbw/apps/Manta/node_modules/electron-builder/src/packager.ts:314:24
From previous event:
    at Packager.doBuild (/home/aitbw/apps/Manta/node_modules/electron-builder/out/packager.js:378:11)
    at /home/aitbw/apps/Manta/node_modules/electron-builder/src/packager.ts:240:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/home/aitbw/apps/Manta/node_modules/electron-builder/out/packager.js:307:11)
    at /home/aitbw/apps/Manta/node_modules/electron-builder/src/builder.ts:278:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/aitbw/apps/Manta/node_modules/electron-builder/out/builder.js:68:21)
    at then (/home/aitbw/apps/Manta/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (/home/aitbw/apps/Manta/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/home/aitbw/apps/Manta/node_modules/electron-builder/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/home/aitbw/apps/Manta/node_modules/electron-builder/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/home/aitbw/apps/Manta/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/aitbw/apps/Manta/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm using `icns2png` version 1.5, `graphicsmagick` version 1.3.27 and `NodeJS` version 8.9.1

Thanks! And keep up the great work :D

**Comment by hql287** [comment]
@aitbw Hey thanks for reporting this. I got this error too (after I merged #125). To build for Linux, simply remove the lines that had been added by the PR #125.

**Comment by aitbw** [comment]
Thanks for the quick reply, @hql287! Managed to get a successful build and now the app is up and running! 🎉

**Comment by hql287** [comment]
@aitbw Glad to know that it's working for you now. If you run into another problem, feel free to open a new ticket (but hopefully not 😁)
